// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp639Vnu7ytsfHJbNzioaViGKL6iwtR0o',
    appId: '1:18403408915:web:7ac9bf228ec17b19ba93e6',
    messagingSenderId: '18403408915',
    projectId: 'neighbourhub-c0dfc',
    authDomain: 'neighbourhub-c0dfc.firebaseapp.com',
    storageBucket: 'neighbourhub-c0dfc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQrI0wv7DNXVUO0bLqmJ7DMWgfgwy1p64',
    appId: '1:18403408915:android:2525d1c67e60eefaba93e6',
    messagingSenderId: '18403408915',
    projectId: 'neighbourhub-c0dfc',
    storageBucket: 'neighbourhub-c0dfc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp639Vnu7ytsfHJbNzioaViGKL6iwtR0o',
    appId: '1:18403408915:web:d52b798c189457d1ba93e6',
    messagingSenderId: '18403408915',
    projectId: 'neighbourhub-c0dfc',
    authDomain: 'neighbourhub-c0dfc.firebaseapp.com',
    storageBucket: 'neighbourhub-c0dfc.firebasestorage.app',
  );
}
